Added the translation of start as experiment
WillemJiang/InnerSourcePatterns pull request #10
Opened 2022-12-06 07:51 UTC by WillemJiang

https://github.com/WillemJiang/open-source-camp/issues/38

2022-12-17 15:18 UTC, hncslwx requested changes

2022-12-17 15:18 UTC, hncslwx commented on translation/cn/patterns/start-as-experiment.md
> +考虑将实验结束时指定为_支点_、_变化_或_暂停_点，以重新评估。还可以考虑建立一个[评审委员会](review-committee.md)，通过参与增加管理层认同的机会。根据公司文化，在实验中加入适当的指标[First Steps With Metrics]（.../.../.../patterns/1-initial/introducing-metrics-innersource.md）可能
[跨团队的项目评估]

2022-12-17 15:18 UTC, hncslwx commented on translation/cn/patterns/start-as-experiment.md
> +- 实验失败的可能性被理解和接受。支持管理人员的个人风险被降至最低。
管理人员支持内源的个人风险被降至最低。

2022-12-21 07:48 UTC, WillemJiang commented on translation/cn/patterns/start-as-experiment.md
> +考虑将实验结束时指定为_支点_、_变化_或_暂停_点，以重新评估。还可以考虑建立一个[评审委员会](review-committee.md)，通过参与增加管理层认同的机会。根据公司文化，在实验中加入适当的指标[First Steps With Metrics]（.../.../.../patterns/1-initial/introducing-metrics-innersource.md）可能
已采纳。

2022-12-21 07:48 UTC, WillemJiang commented on translation/cn/patterns/start-as-experiment.md
> +- 实验失败的可能性被理解和接受。支持管理人员的个人风险被降至最低。
已采纳。

2022-12-21 08:04 UTC, merged