Added the translation of dedicated community leader
WillemJiang/InnerSourcePatterns pull request #11
Opened 2022-12-06 08:20 UTC by WillemJiang

https://github.com/WillemJiang/open-source-camp/issues/28

2022-12-10 14:16 UTC, hncslwx requested changes

2022-12-10 14:16 UTC, hncslwx commented on translation/cn/patterns/dedicated-community-leader.md
> +- 管理层没有被说服提供超过有限的预算来资助一个兼职的社群领袖，只是。
管理层没有被说服，只能提供有限的预算来资助一个兼职的社群领导。

2022-12-10 14:16 UTC, hncslwx commented on translation/cn/patterns/dedicated-community-leader.md
> +敬业的社群领袖
专职的社群领导

2022-12-10 14:16 UTC, hncslwx commented on translation/cn/patterns/dedicated-community-leader.md
> +你如何确保一个新的InnerSource倡议有合适的[社群领袖](http://www.artofcommunityonline.org/)来扩大其影响？
“领袖“ 改 “领导”

2022-12-10 14:16 UTC, hncslwx commented on translation/cn/patterns/dedicated-community-leader.md
> +- 最初选定的社区领袖在开源工作模式方面几乎没有经验。
“领袖“ 改 “领导”

2022-12-10 14:16 UTC, hncslwx commented on translation/cn/patterns/dedicated-community-leader.md
> +- 最初选定的开发者社区领袖在公司内部没有广泛的社交网络。
“领袖“ 改 “领导”

2022-12-10 14:16 UTC, hncslwx commented on translation/cn/patterns/dedicated-community-leader.md
> +选择一个社群领袖，他：
“领袖“ 改 “领导人”

2022-12-10 14:16 UTC, hncslwx commented on translation/cn/patterns/dedicated-community-leader.md
> +授权社群领袖将其100%的时间用于社群工作，包括沟通和开发。告知管理层，在对社群管理进行改革时，需要对社群的意见保持敏感。理想情况下，授权社群自己提名社群领袖。
“领袖“ 改 “领导”

2022-12-10 14:16 UTC, hncslwx commented on translation/cn/patterns/dedicated-community-leader.md
> +一个具有上述属性的社群领袖将为公司带来面子，体现出公司对InnerSource的承诺。这将使他社交网络中的其他同事更有可能跟随他的步伐，为InnerSource做出贡献。随着时间的推移，他或她将能够建立一个稳定的核心开发人员团队，从而增加InnerSource项目的成功机会。通过说服公司内部足够多的人相信InnerSource的潜力，他或她将为公司文化向社区文化的转变做出重要贡献。
“领袖“ 改 “领导”

2022-12-10 14:16 UTC, hncslwx commented on translation/cn/patterns/dedicated-community-leader.md
> +拥有优秀而敬业的社群领袖是InnerSource项目成功的先决条件。然而，这并不是银弹。InnerSource有许多挑战，超出了社群领袖可以解决的范围，如预算、法律、财政或其他组织挑战。
“领袖“ 改 “领导”

2022-12-11 06:18 UTC, WillemJiang commented on translation/cn/patterns/dedicated-community-leader.md
> +敬业的社群领袖
已修改。

2022-12-11 06:20 UTC, WillemJiang commented on translation/cn/patterns/dedicated-community-leader.md
> +- 管理层没有被说服提供超过有限的预算来资助一个兼职的社群领袖，只是。
已修改。

2022-12-11 06:20 UTC, WillemJiang commented on translation/cn/patterns/dedicated-community-leader.md
> +你如何确保一个新的InnerSource倡议有合适的[社群领袖](http://www.artofcommunityonline.org/)来扩大其影响？
已修改。

2022-12-11 06:27 UTC, WillemJiang commented on translation/cn/patterns/dedicated-community-leader.md
> +拥有优秀而敬业的社群领袖是InnerSource项目成功的先决条件。然而，这并不是银弹。InnerSource有许多挑战，超出了社群领袖可以解决的范围，如预算、法律、财政或其他组织挑战。
已修改。

2022-12-11 06:27 UTC, WillemJiang commented on translation/cn/patterns/dedicated-community-leader.md
> +一个具有上述属性的社群领袖将为公司带来面子，体现出公司对InnerSource的承诺。这将使他社交网络中的其他同事更有可能跟随他的步伐，为InnerSource做出贡献。随着时间的推移，他或她将能够建立一个稳定的核心开发人员团队，从而增加InnerSource项目的成功机会。通过说服公司内部足够多的人相信InnerSource的潜力，他或她将为公司文化向社区文化的转变做出重要贡献。
已修改。

2022-12-11 06:27 UTC, WillemJiang commented on translation/cn/patterns/dedicated-community-leader.md
> +授权社群领袖将其100%的时间用于社群工作，包括沟通和开发。告知管理层，在对社群管理进行改革时，需要对社群的意见保持敏感。理想情况下，授权社群自己提名社群领袖。
已修改。

2022-12-11 06:27 UTC, WillemJiang commented on translation/cn/patterns/dedicated-community-leader.md
> +选择一个社群领袖，他：
已修改。

2022-12-11 06:28 UTC, WillemJiang commented on translation/cn/patterns/dedicated-community-leader.md
> +- 最初选定的社区领袖在开源工作模式方面几乎没有经验。
已修改。

2022-12-11 07:53 UTC, merged