Added the translation of crossteam project valuation
WillemJiang/InnerSourcePatterns pull request #12
Opened 2022-12-07 12:44 UTC by WillemJiang

https://github.com/WillemJiang/open-source-camp/issues/27

2022-12-17 15:09 UTC, hncslwx requested changes

2022-12-17 15:09 UTC, hncslwx commented on translation/cn/patterns/crossteam-project-valuation.md
> +* 你负责一个跨团队，为作为公司业务提供的平台服务的项目。
你负责一个跨团队项目，为公司其他团队提供平台服务。

2022-12-17 15:09 UTC, hncslwx commented on translation/cn/patterns/crossteam-project-valuation.md
> +定义一个如何重视跨团队项目的模式和模型。
定义一个如何评估跨团队项目价值的模式和模型。

2022-12-17 15:09 UTC, hncslwx commented on translation/cn/patterns/crossteam-project-valuation.md
> +这样的模式给了我们提供一个需要关注和放大公司的高价值合作的工具。
这种模式给我们提供了一个需要关注和放大公司的高价值合作的工具。

2022-12-17 15:09 UTC, hncslwx commented on translation/cn/patterns/crossteam-project-valuation.md
> +描述一个跨团队的工作价值是一个衡量大家一起完成的 _工作量有多大_ 的量化练习。
衡量一个跨团队的工作价值是一个量化大家一起完成的工作 _怎么就更多_ 的练习。

2022-12-17 15:09 UTC, hncslwx commented on translation/cn/patterns/crossteam-project-valuation.md
> +你可以创建一个模型来计算这个共同协同的过程（带来的价值）。
有一个常见的流程，你可以用它来创建一个模型，用来计算这个协同带来的价值。

2022-12-17 15:09 UTC, hncslwx commented on translation/cn/patterns/crossteam-project-valuation.md
> +我们的想法是让专家组能够大成一致："我们不知道到底要花多长时间，但我们都同意至少要花这么多时间"。
达成一致

2022-12-17 15:09 UTC, hncslwx commented on translation/cn/patterns/crossteam-project-valuation.md
> +具体来说，你应该估计出使用你的项目的_最大_合理时间，以及消费者在其他方面自制、使用和维护他们自己的解决方案的_最小_合理时间。
“在其他方面” 改为 "如果“

2022-12-17 15:09 UTC, hncslwx commented on translation/cn/patterns/crossteam-project-valuation.md
> +1. 通过上述公式节省的原始时间。 既然我们都确信这个公式会产生一个低于真实节省的小时数的数字，你就可以有信心，就项目投入这一点对你来说是稳赚的。
“项目投入到节省的时间，对你来说是稳赚的。”

2022-12-17 15:09 UTC, hncslwx commented on translation/cn/patterns/crossteam-project-valuation.md
> +1. 无论你感觉如何。 拥有一个估值公式的一个有益的副作用是，它自然会迫使大家对项目消费者提供价值的关键使用点进行测量。
只要你觉得好就行。

2022-12-17 15:09 UTC, hncslwx commented on translation/cn/patterns/crossteam-project-valuation.md
> +* 定义跨团队项目所提供的价值，促进它实际上为公司产生更大的价值。
“促进” 改为 “可能导致”

2022-12-19 06:57 UTC, WillemJiang commented on translation/cn/patterns/crossteam-project-valuation.md
> +* 你负责一个跨团队，为作为公司业务提供的平台服务的项目。
已采纳。

2022-12-19 06:58 UTC, WillemJiang commented on translation/cn/patterns/crossteam-project-valuation.md
> +定义一个如何重视跨团队项目的模式和模型。
已采纳。

2022-12-19 06:59 UTC, WillemJiang commented on translation/cn/patterns/crossteam-project-valuation.md
> +这样的模式给了我们提供一个需要关注和放大公司的高价值合作的工具。
已采纳。

2022-12-19 07:03 UTC, WillemJiang commented on translation/cn/patterns/crossteam-project-valuation.md
> +描述一个跨团队的工作价值是一个衡量大家一起完成的 _工作量有多大_ 的量化练习。
已采纳。

2022-12-19 07:17 UTC, WillemJiang commented on translation/cn/patterns/crossteam-project-valuation.md
> +你可以创建一个模型来计算这个共同协同的过程（带来的价值）。
已采纳。

2022-12-19 07:17 UTC, WillemJiang commented on translation/cn/patterns/crossteam-project-valuation.md
> +我们的想法是让专家组能够大成一致："我们不知道到底要花多长时间，但我们都同意至少要花这么多时间"。
已采纳。

2022-12-19 07:17 UTC, WillemJiang commented on translation/cn/patterns/crossteam-project-valuation.md
> +具体来说，你应该估计出使用你的项目的_最大_合理时间，以及消费者在其他方面自制、使用和维护他们自己的解决方案的_最小_合理时间。
已采纳。

2022-12-19 07:17 UTC, WillemJiang commented on translation/cn/patterns/crossteam-project-valuation.md
> +1. 通过上述公式节省的原始时间。 既然我们都确信这个公式会产生一个低于真实节省的小时数的数字，你就可以有信心，就项目投入这一点对你来说是稳赚的。
已采纳。

2022-12-19 07:17 UTC, WillemJiang commented on translation/cn/patterns/crossteam-project-valuation.md
> +1. 无论你感觉如何。 拥有一个估值公式的一个有益的副作用是，它自然会迫使大家对项目消费者提供价值的关键使用点进行测量。
已采纳。

2022-12-21 07:43 UTC, WillemJiang commented on translation/cn/patterns/crossteam-project-valuation.md
> +* 定义跨团队项目所提供的价值，促进它实际上为公司产生更大的价值。
已采纳。

2022-12-21 07:43 UTC, merged