Added the translation of review committee
WillemJiang/InnerSourcePatterns pull request #13
Opened 2022-12-07 12:45 UTC by WillemJiang

https://github.com/WillemJiang/open-source-camp/issues/36

2022-12-17 14:09 UTC, hncslwx requested changes

2022-12-17 14:09 UTC, hncslwx commented on translation/cn/patterns/review-committee.md
> +- 管理者将他们熟悉的工具应用于InnerSource，以获得所需的关于InnerSource 计划内部运作的信息量和控制权。这种熟悉程度将使他们更有可能签署 InnerSource 计划，并给予 InnerSource 项目所需的自由度。
”信息量“ 改为 “足量信息”

2022-12-17 14:09 UTC, hncslwx commented on translation/cn/patterns/review-committee.md
> +- 评审委员会成员有权作为以集体评议的方式决定哪些InnerSource项目将获得通用资源的支持，特别是资金。
删除“作为”

2022-12-17 14:09 UTC, hncslwx commented on translation/cn/patterns/review-committee.md
> +- 每个InnerSource项目都要有机会对评审委员会一次会议上收到的反馈做出反应，直到下一次会议，以避免过早地关闭项目。
每个InnerSource项目都要有对评审委员会会议上收到的反馈做出反应的机会

2022-12-19 06:30 UTC, WillemJiang commented on translation/cn/patterns/review-committee.md
> +- 管理者将他们熟悉的工具应用于InnerSource，以获得所需的关于InnerSource 计划内部运作的信息量和控制权。这种熟悉程度将使他们更有可能签署 InnerSource 计划，并给予 InnerSource 项目所需的自由度。
已采纳。

2022-12-19 06:31 UTC, WillemJiang commented on translation/cn/patterns/review-committee.md
> +- 评审委员会成员有权作为以集体评议的方式决定哪些InnerSource项目将获得通用资源的支持，特别是资金。
已采纳。

2022-12-19 06:44 UTC, WillemJiang commented on translation/cn/patterns/review-committee.md
> +- 每个InnerSource项目都要有机会对评审委员会一次会议上收到的反馈做出反应，直到下一次会议，以避免过早地关闭项目。
已采纳。

2022-12-21 07:42 UTC, merged