Added the translation of gig marketplace
WillemJiang/InnerSourcePatterns pull request #15
Opened 2022-12-07 13:58 UTC by WillemJiang

https://github.com/WillemJiang/open-source-camp/issues/30

2022-12-22 09:37 UTC, hncslwx requested changes

2022-12-22 09:37 UTC, hncslwx commented on translation/cn/patterns/gig-marketplace.md
> +* 员工不了解如何做出对他们职业发现有利的贡献。
“职业发展“

2022-12-22 09:37 UTC, hncslwx commented on translation/cn/patterns/gig-marketplace.md
> +你已经成功地在公司创建了一个内源项目，并得到了高级管理层、中级管理层和开发人员的支持。 然而，在将近一年之后，除了最初创建内源项目的团队之外，很少有人对这些项目做出实际贡献。 在采访了所有相关方后，主要的症结似乎是很难知道如果开发者选择参与内源项目，他们将被要求做出多少时间承诺，以及他们个人将如何受益。也没有统一的方式来宣传为贡献者提供的机会，他们会被要求做什么，以及大概需要多长时间。 经理们都
“也没有统一的方式来宣传为贡献者提供的机会，” 改为 “没有统一的方式来告知能够贡献者提供什么样的机会，”

2022-12-22 09:37 UTC, hncslwx commented on translation/cn/patterns/gig-marketplace.md
> +那些希望接受零工的人应该首先由零工的所有者进行审查，以确定该员工是否具备必要的技能，并由其经理分配时间来完成零工。
“并由其经理分配时间来完成零工。” 改为 “以及他的经理分配给他完成零工的时间。”

2022-12-22 09:37 UTC, hncslwx commented on translation/cn/patterns/gig-marketplace.md
> +内源零工市场极大地增加了内源项目的数量以及参与这些项目的员工人数。零工市场的自我激励到性质提高了员工的工作满意度，因为他们可以对自己的工作和公司内部的合作伙伴有一定程度的选择。 员工们清楚地了解他们所签署的是什么，以及他们能从这种经历中得到什么。经理们能够更好地估计和跟踪员工在内源项目上的时间承诺，认可他们的个人努力，并将完成零工作为验证他们具体技能的一种方式。 经理们还能够利用其员工可能遇到的
“零工市场的自我激励到性质提高了员工的工作满意度，“ 改成 “零工市场的自我导向性提高了员工的工作满意度，”

2022-12-26 02:38 UTC, WillemJiang commented on translation/cn/patterns/gig-marketplace.md
> +* 员工不了解如何做出对他们职业发现有利的贡献。
已采纳。

2022-12-26 02:39 UTC, WillemJiang commented on translation/cn/patterns/gig-marketplace.md
> +你已经成功地在公司创建了一个内源项目，并得到了高级管理层、中级管理层和开发人员的支持。 然而，在将近一年之后，除了最初创建内源项目的团队之外，很少有人对这些项目做出实际贡献。 在采访了所有相关方后，主要的症结似乎是很难知道如果开发者选择参与内源项目，他们将被要求做出多少时间承诺，以及他们个人将如何受益。也没有统一的方式来宣传为贡献者提供的机会，他们会被要求做什么，以及大概需要多长时间。 经理们都
改为 “没有统一的方式来告知能够为贡献者提供什么样的机会，”

2022-12-26 02:40 UTC, WillemJiang commented on translation/cn/patterns/gig-marketplace.md
> +那些希望接受零工的人应该首先由零工的所有者进行审查，以确定该员工是否具备必要的技能，并由其经理分配时间来完成零工。
已采纳。

2022-12-26 02:41 UTC, WillemJiang commented on translation/cn/patterns/gig-marketplace.md
> +内源零工市场极大地增加了内源项目的数量以及参与这些项目的员工人数。零工市场的自我激励到性质提高了员工的工作满意度，因为他们可以对自己的工作和公司内部的合作伙伴有一定程度的选择。 员工们清楚地了解他们所签署的是什么，以及他们能从这种经历中得到什么。经理们能够更好地估计和跟踪员工在内源项目上的时间承诺，认可他们的个人努力，并将完成零工作为验证他们具体技能的一种方式。 经理们还能够利用其员工可能遇到的
已采纳。

2022-12-26 02:52 UTC, merged