Added the translation of repository-activity-score
WillemJiang/InnerSourcePatterns pull request #16
Opened 2022-12-08 02:59 UTC by WillemJiang

https://github.com/WillemJiang/open-source-camp/issues/35

2022-12-12 16:18 UTC, hncslwx requested changes

2022-12-12 16:18 UTC, hncslwx commented on translation/cn/patterns/repository-activity-score.md
> +InnerSource项目应以**何种顺序**呈现？典型的排名指标，如*GitHub星级*、*复刻（fork）数*、*提交数*、*代码行*、*最后更新*，都不足以简明地表明项目的活动。
*GitHub星级* 改为 *GitHub星数*

2022-12-12 16:18 UTC, hncslwx commented on translation/cn/patterns/repository-activity-score.md
> +代码仓活动评分是一个数值，代表InnerSource项目的（GitHub）活动。它是由GitHub星级、监视和复刻等代码仓库统计数据自动得出的，并可以用其他工具或人工评估的KPI来进行补充。
“活动评分” 改为 ”活跃评分”；
“代表InnerSource项目的（GitHub）活动” 改为 “代表内源项目（在GitHub上）活跃程度；”
“GitHub星级、监视和复刻等“ 改为 “GitHub星数、关注和复刻等”

2022-12-12 16:18 UTC, hncslwx commented on translation/cn/patterns/repository-activity-score.md
> +拥有贡献指南、积极参与和问题（公共backlog）的项目也会获得更高的排名。
“积极参与“ 后面加 “的统计数据”

2022-12-12 16:18 UTC, hncslwx commented on translation/cn/patterns/repository-activity-score.md
> +仓库活动评分是一个基于GitHub API的简单计算。它可以完全自动化，并容易适应新的需求。
活跃评分

2022-12-12 16:18 UTC, hncslwx commented on translation/cn/patterns/repository-activity-score.md
> +感谢InnerSource Commons社区以迅雷不及掩耳之势提供的建议，以及大量有益的意见，不断完善这个模式。特别感谢：
“以迅雷不及掩耳之势提供的建议” 改为 “光速提供的建议”

2022-12-16 01:03 UTC, WillemJiang commented on translation/cn/patterns/repository-activity-score.md
> +InnerSource项目应以**何种顺序**呈现？典型的排名指标，如*GitHub星级*、*复刻（fork）数*、*提交数*、*代码行*、*最后更新*，都不足以简明地表明项目的活动。
已采纳。

2022-12-16 01:06 UTC, WillemJiang commented on translation/cn/patterns/repository-activity-score.md
> +感谢InnerSource Commons社区以迅雷不及掩耳之势提供的建议，以及大量有益的意见，不断完善这个模式。特别感谢：
已采纳。

2022-12-16 01:06 UTC, WillemJiang commented on translation/cn/patterns/repository-activity-score.md
> +仓库活动评分是一个基于GitHub API的简单计算。它可以完全自动化，并容易适应新的需求。
已采纳。

2022-12-16 01:08 UTC, WillemJiang commented on translation/cn/patterns/repository-activity-score.md
> +拥有贡献指南、积极参与和问题（公共backlog）的项目也会获得更高的排名。
已采纳。

2022-12-16 01:11 UTC, WillemJiang commented on translation/cn/patterns/repository-activity-score.md
> +代码仓活动评分是一个数值，代表InnerSource项目的（GitHub）活动。它是由GitHub星级、监视和复刻等代码仓库统计数据自动得出的，并可以用其他工具或人工评估的KPI来进行补充。
已采纳。

2022-12-19 06:43 UTC, merged