Added the translation of innersource-portal
WillemJiang/InnerSourcePatterns pull request #17
Opened 2022-12-08 03:02 UTC by WillemJiang

https://github.com/WillemJiang/open-source-camp/issues/32

2022-12-10 14:49 UTC, anzipomelo requested changes

2022-12-10 14:49 UTC, anzipomelo commented on translation/cn/patterns/innersource-portal.md
> +潜在的贡献者很难找到他们感兴趣的InnerSource项目。通过创建一个索引所有可用的InnerSource项目信息的内部网站，你可以让贡献者了解他们可能感兴趣的项目，并帮助InnerSource项目的负责人发展外部受众。
潜在的贡献者很难找到他们感兴趣的InnerSource项目。
你可以通过创建一个索引所有可用的InnerSource项目信息的内部网站，让贡献者了解他们可能感兴趣的项目，也可以让InnerSource项目负责人发展外部受众。

2022-12-10 14:49 UTC, anzipomelo commented on translation/cn/patterns/innersource-portal.md
> +你的组织的InnerSource项目正在增加，但潜在的贡献者却没有办法轻易找到这些项目。
你组织中的InnerSource项目逐渐增加，但潜在的贡献者却没有办法方便地找到这些项目。

2022-12-10 14:49 UTC, anzipomelo commented on translation/cn/patterns/innersource-portal.md
> +你正试图在你的组织内建立一个InnerSource实践。 你知道有些项目正在使用InnerSource模式运行，但它们的存在只是通过口耳相传、电子邮件或与其他员工的旁听对话来传达。 因此，InnerSource项目负责人发现很难吸引贡献者。
你正尝试在你的组织内建立一个InnerSource实践。 
你知道有些项目正在使用InnerSource模式运行，但它们的存在只是通过口耳相传、电子邮件或与其他员工的旁听对话来传达。 因此，InnerSource项目负责人发现很难吸引贡献者。

2022-12-10 14:49 UTC, anzipomelo commented on translation/cn/patterns/innersource-portal.md
> +没有一个单一的、共享的资源网站可以供整个组织的员工访问，这样的资源网站可以使他们能够轻松发现所有正在进行的InnerSource项目。 这严重制约了每个InnerSource项目的发展。
没有一个专注于分享InnerSource项目信息的网站可以供整个组织的员工去方便地使用来了解所有正在进行的InnerSource项目。 这严重制约了每个InnerSource项目的发展。

2022-12-10 14:49 UTC, anzipomelo commented on translation/cn/patterns/innersource-portal.md
> +如何才能帮助所有InnerSource项目提高其知名度，让更多的人了解，并吸引整个组织的贡献者？
做什么才能帮助所有InnerSource项目尽可能高地提高其知名度，并吸引整个组织范围中的贡献者呢？

2022-12-10 14:49 UTC, anzipomelo commented on translation/cn/patterns/innersource-portal.md
> +* InnerSource门户网站使InnerSource项目负责人能够向整个组织的受众宣传他们的项目。 由于知名度的提高，他们吸引了比以往更大的贡献者群体。
InnerSource门户网站使InnerSource项目负责人能够向整个组织的受众宣传他们的项目。 由于曝光度的提高，他们吸引了比以往更大的贡献者群体。

2022-12-10 14:49 UTC, anzipomelo commented on translation/cn/patterns/innersource-portal.md
> +* 对于那些希望参与InnerSource项目的人来说，InnerSource门户网站使他们能够准确地发现他们感兴趣的机会，根据他们的具体标准同时搜索所有可用的InnerSource项目。
对于那些希望参与InnerSource项目的人来说，InnerSource 门户允许他们根据特定标准同时搜索所有可用的 InnerSource 项目，从而准确发现他们感兴趣的机会类型

2022-12-10 14:49 UTC, anzipomelo commented on translation/cn/patterns/innersource-portal.md
> +
* 安旭

2022-12-10 14:49 UTC, anzipomelo commented on translation/cn/patterns/innersource-portal.md
> +* **Elbit Systems**使用了这个模式，并在上面添加了游戏化内容。
* **Elbit Systems**使用了这个模式，并在顶部添加了游戏化内容。

2022-12-10 14:49 UTC, anzipomelo commented on translation/cn/patterns/innersource-portal.md
> +* 在这种情况下，InnerSource 门户模式已经被证明与相关的InnerSource [零工市场](./gig-marketplace.md)模式配合使用效果非常好。
[Gig Marketplace] 是个专有名词，不确定是不是 零工市场。

2022-12-11 03:15 UTC, WillemJiang commented on translation/cn/patterns/innersource-portal.md
> +* **Elbit Systems**使用了这个模式，并在上面添加了游戏化内容。
不是顶部， 是在这个模式的基础之上 ：）

2022-12-11 03:16 UTC, WillemJiang commented on translation/cn/patterns/innersource-portal.md
> +* 在这种情况下，InnerSource 门户模式已经被证明与相关的InnerSource [零工市场](./gig-marketplace.md)模式配合使用效果非常好。
零工还是会容易理解一些。

2022-12-11 06:32 UTC, WillemJiang commented on translation/cn/patterns/innersource-portal.md
> +潜在的贡献者很难找到他们感兴趣的InnerSource项目。通过创建一个索引所有可用的InnerSource项目信息的内部网站，你可以让贡献者了解他们可能感兴趣的项目，并帮助InnerSource项目的负责人发展外部受众。
已修改。

2022-12-11 06:34 UTC, WillemJiang commented on translation/cn/patterns/innersource-portal.md
> +你的组织的InnerSource项目正在增加，但潜在的贡献者却没有办法轻易找到这些项目。
已修改。

2022-12-11 06:37 UTC, WillemJiang commented on translation/cn/patterns/innersource-portal.md
> +你正试图在你的组织内建立一个InnerSource实践。 你知道有些项目正在使用InnerSource模式运行，但它们的存在只是通过口耳相传、电子邮件或与其他员工的旁听对话来传达。 因此，InnerSource项目负责人发现很难吸引贡献者。
优化成 “你知道有些项目正在使用内源模式运行，但它们只是通过口耳相传、电子邮件或与其他员工的旁听对话来获知其存在。 因此，内源项目负责人发现吸引贡献者是件很难做到事情。”

2022-12-11 06:38 UTC, WillemJiang commented on translation/cn/patterns/innersource-portal.md
> +没有一个单一的、共享的资源网站可以供整个组织的员工访问，这样的资源网站可以使他们能够轻松发现所有正在进行的InnerSource项目。 这严重制约了每个InnerSource项目的发展。
已修改。

2022-12-11 06:39 UTC, WillemJiang commented on translation/cn/patterns/innersource-portal.md
> +如何才能帮助所有InnerSource项目提高其知名度，让更多的人了解，并吸引整个组织的贡献者？
已修改。

2022-12-11 06:40 UTC, WillemJiang commented on translation/cn/patterns/innersource-portal.md
> +* InnerSource门户网站使InnerSource项目负责人能够向整个组织的受众宣传他们的项目。 由于知名度的提高，他们吸引了比以往更大的贡献者群体。
已修改。

2022-12-11 06:42 UTC, WillemJiang commented on translation/cn/patterns/innersource-portal.md
> +
已添加。

2022-12-12 07:37 UTC, WillemJiang commented on translation/cn/patterns/innersource-portal.md
> +* 对于那些希望参与InnerSource项目的人来说，InnerSource门户网站使他们能够准确地发现他们感兴趣的机会，根据他们的具体标准同时搜索所有可用的InnerSource项目。
已修改。

2022-12-12 07:38 UTC, merged