Added the translation of document-your-guiding-principles
WillemJiang/InnerSourcePatterns pull request #19
Opened 2022-12-08 13:10 UTC by WillemJiang

https://github.com/WillemJiang/open-source-camp/issues/29

2022-12-26 06:58 UTC, hncslwx requested changes

2022-12-26 06:58 UTC, hncslwx commented on translation/cn/patterns/document-your-guiding-principles.md
> +一个项目的所有利益相关者都是潜在的贡献者，并被作为贡献者对待和并予以支持。
“和并予以支持” 删除 “和”

2022-12-26 06:58 UTC, hncslwx commented on translation/cn/patterns/document-your-guiding-principles.md
> +(6) 奖励受信任的承诺
奖励 Trusted Committer 人员

2022-12-26 06:58 UTC, hncslwx commented on translation/cn/patterns/document-your-guiding-principles.md
> +同时，我们努力成为一个工程师可以自由地跨边界工作的公司，商业专家经常要求我们在我们的核心领域之外的领域作出贡献。
“商业专家” 改为 “业务优先事项”

2022-12-26 06:58 UTC, hncslwx commented on translation/cn/patterns/document-your-guiding-principles.md
> +  - 适当的遥测是到位的
具有适当的遥测技术

2022-12-26 06:58 UTC, hncslwx commented on translation/cn/patterns/document-your-guiding-principles.md
> +  - 适当的测试覆盖率已经到位
具有适当的测试覆盖率

2022-12-26 06:58 UTC, hncslwx commented on translation/cn/patterns/document-your-guiding-principles.md
> +  - 正确的架构和设计
合理的架构和设计

2022-12-26 06:58 UTC, hncslwx commented on translation/cn/patterns/document-your-guiding-principles.md
> +- **任人唯贤**：BIOS项目成员的权力是基于他们的优点，也就是基于他们贡献的质量和数量。
“优点“ 改为 “价值“ 或 “成绩”

2022-12-27 12:51 UTC, WillemJiang commented on translation/cn/patterns/document-your-guiding-principles.md
> +一个项目的所有利益相关者都是潜在的贡献者，并被作为贡献者对待和并予以支持。
已采纳。

2022-12-27 12:52 UTC, WillemJiang commented on translation/cn/patterns/document-your-guiding-principles.md
> +(6) 奖励受信任的承诺
已采纳。

2022-12-27 12:53 UTC, WillemJiang commented on translation/cn/patterns/document-your-guiding-principles.md
> +同时，我们努力成为一个工程师可以自由地跨边界工作的公司，商业专家经常要求我们在我们的核心领域之外的领域作出贡献。
已采纳。

2022-12-27 12:53 UTC, WillemJiang commented on translation/cn/patterns/document-your-guiding-principles.md
> +  - 适当的遥测是到位的
已采纳。

2022-12-27 12:57 UTC, WillemJiang commented on translation/cn/patterns/document-your-guiding-principles.md
> +- **任人唯贤**：BIOS项目成员的权力是基于他们的优点，也就是基于他们贡献的质量和数量。
把 “优点”改成 “功绩”了。

2022-12-27 12:57 UTC, WillemJiang commented on translation/cn/patterns/document-your-guiding-principles.md
> +  - 正确的架构和设计
已采纳。

2022-12-27 12:57 UTC, WillemJiang commented on translation/cn/patterns/document-your-guiding-principles.md
> +  - 适当的测试覆盖率已经到位
已采纳。

2022-12-28 03:05 UTC, merged