Update the translation of Maturity model
WillemJiang/InnerSourcePatterns pull request #20
Opened 2022-12-09 08:27 UTC by WillemJiang

https://github.com/WillemJiang/open-source-camp/issues/33

2022-12-26 03:53 UTC, hncslwx requested changes

2022-12-26 03:53 UTC, hncslwx commented on translation/cn/patterns/maturity-model.md
> +贡献者主动参与到内源项目可以让项目获得更好的发展。因此，需要让贡献和追求完美的技术目标之间达到平衡。
需要在使贡献更容易和追求完美的技术目标之间达到平衡。

2022-12-26 03:53 UTC, hncslwx commented on translation/cn/patterns/maturity-model.md
> +* DP-0: 互相区隔的开发团队。各团队有自己的开发流程和工具。没有和其他团队共享知识和工件。
工件 改为 作品

2022-12-26 03:53 UTC, hncslwx commented on translation/cn/patterns/maturity-model.md
> +* DP-1: 公司内开发团队之间共享代码库。部分团队有自己的CI工具，没有使用公司统一的CI工具。部分团队内部有自己的代码评审流程。但是公司没有统一的代码评审流程。
部分团队有自己的CI流程，没有使用公司统一或标准的CI工具。

2022-12-26 03:53 UTC, hncslwx commented on translation/cn/patterns/maturity-model.md
> +* DP-2: 建设公司级的知识共享库。部分团队使用公司CI工具来使能自己的CI流程。公司存在统一的CI环境和代码检视流程。部分项目已经应用。代码审查会邀请外部团队成员协助完成。
使能 改为 开发

2022-12-26 03:53 UTC, hncslwx commented on translation/cn/patterns/maturity-model.md
> +团队成员内部可以深入学习和了解曾经遇到的问题和解决的方法。为了让团队外部人员了解到曾经遇到的问题，需要建设跨团队共享经验的文化，在企业内鼓励共享成功或失败的经验，促进其他团队的成长。
当在东道主团队中工作时，错误会自动被广泛看见。为了保持贡献水平，企业文化需要庆祝失败，作为大家共同成长和学习的机会。

2022-12-26 03:53 UTC, hncslwx commented on translation/cn/patterns/maturity-model.md
> +* ST-2：个人和团队愿意分享成功和失败的经验。
ST-2：个人和团队在回顾和评审时，愿意分享成功和失败的经验。

2022-12-26 03:53 UTC, hncslwx commented on translation/cn/patterns/maturity-model.md
> +理想情况下，您最终会建立起适当的沟通渠道，这被整个组织中被广泛使用。这些渠道将聚焦于不同的目标（公告、用户支持、开发渠道、非正式讨论、等）。你将逐渐形成一套最佳实践，例如采用网络礼仪准则，为每一个新的内源项目开辟一套成熟的标准化沟通渠道（即时存档的、可公开访问的、可搜索的）。
“这被整个组织中被广泛使用。”改为 “并被整个组织广泛使用。”
“（即时存档的、可公开访问的、可搜索的）。“ 改 为” （消息即时存档、可公开访问、可搜索的渠道）。”

2022-12-26 03:53 UTC, hncslwx commented on translation/cn/patterns/maturity-model.md
> +* LS-2：一些领导人愿意接受反馈，并创造一个让人们感到能够安全反馈的环境。领导者在理解所有成员是否都感到有权力和能够分享时表现出消极的态度。组织鼓励领导者积极寻找对话中没有出现的声音，以求包容。
“一些” 改 “多数“

2022-12-26 03:53 UTC, hncslwx commented on translation/cn/patterns/maturity-model.md
> +* RW-3：奖励不仅由组织提出，社区也会提出他们认为的更有价值的奖励。内源社区有责任决定谁应该得到奖励。内源社区应该声明鼓励协作，并在社区层面给予认可。
“”内源社区应该声明鼓励协作，并在社区层面给予认可。“这一句英文原文没有。

2022-12-26 03:53 UTC, hncslwx commented on translation/cn/patterns/maturity-model.md
> +* SM-3: 有由成熟社区提供的规则和制度，来使对产品的支持和维护正确立。
有成熟社区的规则和制度正式支持产品。

2022-12-26 03:53 UTC, hncslwx commented on translation/cn/patterns/maturity-model.md
> +* RO-2: 内源管理者角色负责治理和支持，包括流程等。识别教育需求，并确保向组织提供教育需求。内源领导和教练负责组织参与内源项目。第一个正式步骤是：定义内源愿景和路标。组织定义了受信任的提交者（trusted committer）角色，不仅为开发团队成员，而且为外部贡献者提供联系/参考。有一个标准的流程描述如何为社区做出贡献，贡献者角色是存在的。数据安全员角色负责管理内源活动留下的操作日志，
识别教育需求，并确保向组织提供所需的教育和培训。

2022-12-27 12:49 UTC, WillemJiang commented on translation/cn/patterns/maturity-model.md
> +贡献者主动参与到内源项目可以让项目获得更好的发展。因此，需要让贡献和追求完美的技术目标之间达到平衡。
已采纳。

2022-12-27 12:49 UTC, WillemJiang commented on translation/cn/patterns/maturity-model.md
> +* DP-0: 互相区隔的开发团队。各团队有自己的开发流程和工具。没有和其他团队共享知识和工件。
已采纳。

2022-12-27 12:49 UTC, WillemJiang commented on translation/cn/patterns/maturity-model.md
> +* DP-1: 公司内开发团队之间共享代码库。部分团队有自己的CI工具，没有使用公司统一的CI工具。部分团队内部有自己的代码评审流程。但是公司没有统一的代码评审流程。
已采纳。

2022-12-27 12:49 UTC, WillemJiang commented on translation/cn/patterns/maturity-model.md
> +* DP-2: 建设公司级的知识共享库。部分团队使用公司CI工具来使能自己的CI流程。公司存在统一的CI环境和代码检视流程。部分项目已经应用。代码审查会邀请外部团队成员协助完成。
已采纳。

2022-12-27 12:49 UTC, WillemJiang commented on translation/cn/patterns/maturity-model.md
> +团队成员内部可以深入学习和了解曾经遇到的问题和解决的方法。为了让团队外部人员了解到曾经遇到的问题，需要建设跨团队共享经验的文化，在企业内鼓励共享成功或失败的经验，促进其他团队的成长。
已采纳。

2022-12-27 12:49 UTC, WillemJiang commented on translation/cn/patterns/maturity-model.md
> +* ST-2：个人和团队愿意分享成功和失败的经验。
已采纳。

2022-12-27 12:49 UTC, WillemJiang commented on translation/cn/patterns/maturity-model.md
> +理想情况下，您最终会建立起适当的沟通渠道，这被整个组织中被广泛使用。这些渠道将聚焦于不同的目标（公告、用户支持、开发渠道、非正式讨论、等）。你将逐渐形成一套最佳实践，例如采用网络礼仪准则，为每一个新的内源项目开辟一套成熟的标准化沟通渠道（即时存档的、可公开访问的、可搜索的）。
（消息即时存档、可公开访问、可搜索的渠道） 改为 （消息即时存档、可公开访问、提供搜索功能）

2022-12-27 12:49 UTC, WillemJiang commented on translation/cn/patterns/maturity-model.md
> +* LS-2：一些领导人愿意接受反馈，并创造一个让人们感到能够安全反馈的环境。领导者在理解所有成员是否都感到有权力和能够分享时表现出消极的态度。组织鼓励领导者积极寻找对话中没有出现的声音，以求包容。
已采纳。

2022-12-27 12:49 UTC, WillemJiang commented on translation/cn/patterns/maturity-model.md
> +* RW-3：奖励不仅由组织提出，社区也会提出他们认为的更有价值的奖励。内源社区有责任决定谁应该得到奖励。内源社区应该声明鼓励协作，并在社区层面给予认可。
已删除。

2022-12-27 12:49 UTC, WillemJiang commented on translation/cn/patterns/maturity-model.md
> +* SM-3: 有由成熟社区提供的规则和制度，来使对产品的支持和维护正确立。
已采纳。

2022-12-27 12:49 UTC, WillemJiang commented on translation/cn/patterns/maturity-model.md
> +* RO-2: 内源管理者角色负责治理和支持，包括流程等。识别教育需求，并确保向组织提供教育需求。内源领导和教练负责组织参与内源项目。第一个正式步骤是：定义内源愿景和路标。组织定义了受信任的提交者（trusted committer）角色，不仅为开发团队成员，而且为外部贡献者提供联系/参考。有一个标准的流程描述如何为社区做出贡献，贡献者角色是存在的。数据安全员角色负责管理内源活动留下的操作日志，
已采纳。

2022-12-28 03:05 UTC, merged