Update the translation of rfc-template
WillemJiang/InnerSourcePatterns pull request #21
Opened 2022-12-09 08:28 UTC by WillemJiang

https://github.com/WillemJiang/open-source-camp/issues/40

2022-12-14 12:56 UTC, hncslwx requested changes

2022-12-14 12:56 UTC, hncslwx commented on translation/cn/templates/rfc.md
> +## 导游级别的介绍
指南级的介绍

2022-12-14 12:56 UTC, hncslwx commented on translation/cn/templates/rfc.md
> +- 使用示例子来解释这个特性。
用示例来解释主要特点。

2022-12-14 12:56 UTC, hncslwx commented on translation/cn/templates/rfc.md
> +- 解释工程师是如何思考这个功能实现的。应该尽可能具体地解释其带来的影响。
删除“实现”

2022-12-16 00:57 UTC, WillemJiang commented on translation/cn/templates/rfc.md
> +## 导游级别的介绍
修改已采纳。

2022-12-19 06:44 UTC, merged