Added the Chinese transaltion of git book
WillemJiang/InnerSourcePatterns pull request #23
Opened 2022-12-22 03:14 UTC by WillemJiang

2022-12-26 03:48 UTC, hncslwx requested changes

2022-12-26 03:48 UTC, hncslwx commented on book/cn/introduction.md
> +![内源模式图书](innersource-patterns-book-cover.jpg)
书名是“内源模式”，删除“图书”两字。

2022-12-26 03:48 UTC, hncslwx commented on book/cn/introduction.md
> +欢迎来到**内源模式书**。
欢迎来到**内源模式**

2022-12-26 03:48 UTC, hncslwx commented on book/cn/toc.md
> +* [临工市场](../../translation/cn/gig-marketplace.md) - E建立一个市场，通过创建一个内部网站，将特定的内源项目需求列为 "Gig"，并明确规定时间和技能要求。 这将使管理人员能够更好地了解员工的时间承诺和专业利益，从而增加获得批准做出内源贡献的可能性。
“零工市场”

2022-12-26 03:48 UTC, hncslwx commented on book/cn/toc.md
> +* [模式模版](../../meta/pattern-template.md)
模板

2022-12-26 03:48 UTC, hncslwx commented on book/cn/toc.md
> +  * [README 模版](../../translation/cn/templates/README-template.md)
模板

2022-12-26 03:48 UTC, hncslwx commented on book/cn/toc.md
> +  * [CONTRIBUTING 模版](../../translation/cn/templates/CONTRIBUTING-template.md)
模板

2022-12-26 03:48 UTC, hncslwx commented on book/cn/toc_template.md
> +* [模式模版](../../meta/pattern-template.md)
模板

2022-12-26 03:48 UTC, hncslwx commented on book/cn/toc_template.md
> +  * [README 模版](../../translation/cn/templates/README-template.md)
模板

2022-12-26 03:48 UTC, hncslwx commented on book/cn/toc_template.md
> +  * [CONTRIBUTING 模版](../../translation/cn/templates/CONTRIBUTING-template.md)
模板

2022-12-27 12:20 UTC, WillemJiang commented on book/cn/introduction.md
> +![内源模式图书](innersource-patterns-book-cover.jpg)
已采纳。

2022-12-27 12:21 UTC, WillemJiang commented on book/cn/introduction.md
> +欢迎来到**内源模式书**。
已采纳。

2022-12-27 12:23 UTC, WillemJiang commented on book/cn/toc.md
> +* [临工市场](../../translation/cn/gig-marketplace.md) - E建立一个市场，通过创建一个内部网站，将特定的内源项目需求列为 "Gig"，并明确规定时间和技能要求。 这将使管理人员能够更好地了解员工的时间承诺和专业利益，从而增加获得批准做出内源贡献的可能性。
已采纳

2022-12-27 12:25 UTC, WillemJiang commented on book/cn/toc.md
> +* [模式模版](../../meta/pattern-template.md)
已采纳

2022-12-27 12:25 UTC, WillemJiang commented on book/cn/toc.md
> +  * [CONTRIBUTING 模版](../../translation/cn/templates/CONTRIBUTING-template.md)
已采纳

2022-12-27 12:25 UTC, WillemJiang commented on book/cn/toc.md
> +  * [README 模版](../../translation/cn/templates/README-template.md)
已采纳

2022-12-27 12:26 UTC, WillemJiang commented on book/cn/toc_template.md
> +* [模式模版](../../meta/pattern-template.md)
已采纳

2022-12-27 12:26 UTC, WillemJiang commented on book/cn/toc_template.md
> +  * [README 模版](../../translation/cn/templates/README-template.md)
已采纳

2022-12-27 12:26 UTC, WillemJiang commented on book/cn/toc_template.md
> +  * [CONTRIBUTING 模版](../../translation/cn/templates/CONTRIBUTING-template.md)
已采纳

2022-12-28 03:04 UTC, merged