Added the translation of communication-tool
WillemJiang/InnerSourcePatterns pull request #8
Opened 2022-12-06 05:55 UTC by WillemJiang

https://github.com/WillemJiang/open-source-camp/issues/22

2022-12-08 15:30 UTC, hncslwx requested changes

2022-12-08 15:30 UTC, hncslwx commented on translation/cn/patterns/communication-tooling.md
> +即使是以书面形式发生，沟通也是以1对1的方式进行。
即使是书面形式的沟通，也是1对1的方式进行的。

2022-12-08 15:30 UTC, hncslwx commented on translation/cn/patterns/communication-tooling.md
> +虽然协调和沟通是以一种临时的方式进行的，导致了信息共享的不连贯性，收到答复的延迟，贡献者倾向于在收到明确的答复前会呼叫多个东道主团队成员。
”虽然协调和沟通是以一种临时的方式进行的“ 改为 “由于协调和沟通是以一种点对点的方式进行的”
“贡献者倾向于“ 改为 “贡献者于是“

2022-12-08 15:30 UTC, hncslwx commented on translation/cn/patterns/communication-tooling.md
> +- 沟通渠道可能与应该接触到的特定群体使用习惯相一致，但不是以沟通目进行选择的。
“以沟通目“ 后面加“标”

2022-12-09 01:06 UTC, WillemJiang commented on translation/cn/patterns/communication-tooling.md
> +即使是以书面形式发生，沟通也是以1对1的方式进行。
已修改。

2022-12-09 01:09 UTC, WillemJiang commented on translation/cn/patterns/communication-tooling.md
> +虽然协调和沟通是以一种临时的方式进行的，导致了信息共享的不连贯性，收到答复的延迟，贡献者倾向于在收到明确的答复前会呼叫多个东道主团队成员。
已修改。

2022-12-09 01:09 UTC, WillemJiang commented on translation/cn/patterns/communication-tooling.md
> +- 沟通渠道可能与应该接触到的特定群体使用习惯相一致，但不是以沟通目进行选择的。
已修改。

2022-12-09 13:57 UTC, merged