Added the translation of RFC
WillemJiang/InnerSourcePatterns pull request #9
Opened 2022-12-06 06:43 UTC by WillemJiang

https://github.com/WillemJiang/open-source-camp/issues/39

2022-12-10 13:18 UTC, hncslwx requested changes

2022-12-10 13:18 UTC, hncslwx commented on translation/cn/patterns/transparent-cross-team-decision-making-using-rfcs.md
> +- 一个InnerSource项目的许多团队共同拥有。
"的许多团队共同拥有" 改为 “由许多团队共同拥有“

2022-12-10 13:18 UTC, hncslwx commented on translation/cn/patterns/transparent-cross-team-decision-making-using-rfcs.md
> +- **DAZN** (10/2021) - DAZN做出技术决定的一种方式是通过RFCs。RFCs仅用于适用于工程范围内流程的决定！RFCs存在于GitHub中。RFCs存在于GitHub仓库中，然后技术标准逐渐被他们的工具和工程师所采用。一个RFC可以由任何工程师提出，并由所有工程师投票表决。如果支持率超过反对率，RFC就会被采纳。值得注意的是，RFC的投票过程还没有经过任何有争议的决定的
RFC的投票过程还没有经过任何有争议的决定的 "压力测试"
建议“RFC的投票过程至今没有因为任何争议的决定引发 "压力测试"”

2022-12-10 13:18 UTC, hncslwx commented on translation/cn/patterns/transparent-cross-team-decision-making-using-rfcs.md
> +多年来，RFCs在开源世界中证明了自己。对于互联网整体而言，RFCs在制定标准方面发挥了重要作用（例如，见[30 Years of RFCs][30-years-of-rfcs]），对于其他开源项目也是如此，它们采用这种方法来促进社区的透明决策（例如，[RUST][rust]，[ZeroMQ][zeromq]）。
多年来，RFCs在开源世界中证明了自己。对于互联网整体而言，RFCs在制定标准方面发挥了重要作用。
两个RFCs 改为 RFC

2022-12-10 13:18 UTC, hncslwx commented on translation/cn/patterns/transparent-cross-team-decision-making-using-rfcs.md
> +多年来，RFCs在开源世界中证明了自己。对于互联网整体而言，RFCs在制定标准方面发挥了重要作用（例如，见[30 Years of RFCs][30-years-of-rfcs]），对于其他开源项目也是如此，它们采用这种方法来促进社区的透明决策（例如，[RUST][rust]，[ZeroMQ][zeromq]）。
多年来，RFCs在开源世界中证明了自己。对于互联网整体而言，RFCs在制定标准方面发挥了重要作用。
两个RFCs 改为 RFC

2022-12-10 13:18 UTC, hncslwx commented on translation/cn/patterns/transparent-cross-team-decision-making-using-rfcs.md
> +InnerSource 项目如果想实现高参与率，并为每个参与者做出最好的决定，就需要想办法在整个软件生命周期中建立易于参与式的环境。发布内部征求意见稿（RFC）文件，可以在设计过程的早期就进行讨论，并促进在参与各方在高参与度下建立解决方案的机会。
”InnerSource” 翻译为 “内源“，这是本文最重要名词，应该给一个中文翻译。

2022-12-10 13:18 UTC, hncslwx commented on translation/cn/patterns/transparent-cross-team-decision-making-using-rfcs.md
> +InnerSource 项目如果想实现高参与率，并为每个参与者做出最好的决定，就需要想办法在整个软件生命周期中建立易于参与式的环境。发布内部征求意见稿（RFC）文件，可以在设计过程的早期就进行讨论，并促进在参与各方在高参与度下建立解决方案的机会。
”InnerSource” 翻译为 “内源“，这是本文最重要名词，应该给一个中文翻译。

2022-12-11 03:05 UTC, WillemJiang commented on translation/cn/patterns/transparent-cross-team-decision-making-using-rfcs.md
> +InnerSource 项目如果想实现高参与率，并为每个参与者做出最好的决定，就需要想办法在整个软件生命周期中建立易于参与式的环境。发布内部征求意见稿（RFC）文件，可以在设计过程的早期就进行讨论，并促进在参与各方在高参与度下建立解决方案的机会。
嗯，“InnerSource”会集中替换成“内源”。

2022-12-11 03:08 UTC, WillemJiang commented on translation/cn/patterns/transparent-cross-team-decision-making-using-rfcs.md
> +- 一个InnerSource项目的许多团队共同拥有。
已修改。

2022-12-11 03:09 UTC, WillemJiang commented on translation/cn/patterns/transparent-cross-team-decision-making-using-rfcs.md
> +- **DAZN** (10/2021) - DAZN做出技术决定的一种方式是通过RFCs。RFCs仅用于适用于工程范围内流程的决定！RFCs存在于GitHub中。RFCs存在于GitHub仓库中，然后技术标准逐渐被他们的工具和工程师所采用。一个RFC可以由任何工程师提出，并由所有工程师投票表决。如果支持率超过反对率，RFC就会被采纳。值得注意的是，RFC的投票过程还没有经过任何有争议的决定的
已修改。

2022-12-11 03:09 UTC, WillemJiang commented on translation/cn/patterns/transparent-cross-team-decision-making-using-rfcs.md
> +多年来，RFCs在开源世界中证明了自己。对于互联网整体而言，RFCs在制定标准方面发挥了重要作用（例如，见[30 Years of RFCs][30-years-of-rfcs]），对于其他开源项目也是如此，它们采用这种方法来促进社区的透明决策（例如，[RUST][rust]，[ZeroMQ][zeromq]）。
已修改。

2022-12-11 03:10 UTC, WillemJiang commented on translation/cn/patterns/transparent-cross-team-decision-making-using-rfcs.md
> +InnerSource 项目如果想实现高参与率，并为每个参与者做出最好的决定，就需要想办法在整个软件生命周期中建立易于参与式的环境。发布内部征求意见稿（RFC）文件，可以在设计过程的早期就进行讨论，并促进在参与各方在高参与度下建立解决方案的机会。
已修改。

2022-12-11 07:54 UTC, merged